### ISSUE TITLE
hp.Int out of min max value

### ISSUE THREAD

**Issue by bensdm** [keras-team/keras-tuner#180]
I am trying to use the library to find the best architecture for my infoVAE. But it seem's that there is an issue with hp.Int as the value is sometimes not between min_value and max_value. This sometimes leads to an error from
 https://github.com/keras-team/keras-tuner/blob/master/kerastuner/engine/hyperparameters.py

`closest_index = np.abs(values - value).argmin()`as values - value is empty

Or am i doing smething wrong

code to reproduce:

```
DATASET_SIZE, input_shape = data.shape

def compute_kernel(x, y, name):
    x_size = tf.shape(x)[0]
    y_size = tf.shape(y)[0]
    dim = tf.shape(x)[1]
    tiled_x = tf.tile(tf.reshape(x, tf.stack(
        [x_size, 1, dim], name=name + 's1')), tf.stack([1, y_size, 1], name=name + 's2'))
    tiled_y = tf.tile(tf.reshape(y, tf.stack(
        [1, y_size, dim], name=name + 's3')), tf.stack([x_size, 1, 1], name=name + 's4'))
    return tf.exp(-tf.reduce_mean(tf.square(tiled_x - tiled_y),
                                  axis=2) / tf.cast(dim, tf.float32))

def compute_mmd(x, y, name):
    x_kernel = compute_kernel(x, x, name+'x')
    y_kernel = compute_kernel(y, y, name+'y')
    xy_kernel = compute_kernel(x, y, name+'xy')
    return tf.reduce_mean(x_kernel) + tf.reduce_mean(y_kernel) - \
        2 * tf.reduce_mean(xy_kernel)


def cust_loss(encoder_input_, encoder_output_, decoder_output_, latent_dim):
    true_samples = tf.random.normal(tf.stack([batch_size, latent_dim]))
    loss_mmd = compute_mmd(true_samples, encoder_output_,'1')
    loss_nll = tf.reduce_mean(tf.square(encoder_input_ - decoder_output_))
    loss = tf.reduce_mean(loss_nll + loss_mmd, name='loss')
    return loss

class MyHyperModel(kerastuner.HyperModel):

    def build(self, hp):
        LATENT_DIM = hp.Int('latent_dim', min_value=2, max_value=12)
        GAUSSIAN_NOISE = hp.Float(
            'gaussian_noise',  min_value=0.001, max_value=0.1, sampling='log')
        N_LAYERS = hp.Int('n_layers', min_value=2, max_value=5)
        # ACTIVATION = hp.Choice('activation',['linear','tanh'])
        hidden_dims = []
        for i in range(N_LAYERS):
            hidden_dims.append(hp.Int('units_layer_'+str(i), min_value=LATENT_DIM+N_LAYERS-i, 
                                                             max_value=128 if i==0 else hidden_dims[-1]))

        encoder_input = tf.keras.Input(shape=(input_shape,), name='enc_input')
        encoder_input_noisy = tf.keras.layers.GaussianNoise(
            GAUSSIAN_NOISE, name="encoder_input_added_noise")(encoder_input)

        x = tf.keras.layers.Dense(
            hidden_dims[0],
            activation='relu')(encoder_input_noisy)
        for d in hidden_dims[1:]:
            x = tf.keras.layers.Dense(d)(x)
            x = tf.keras.layers.BatchNormalization()(x)
            x = tf.keras.layers.Activation('relu')(x)
            x = tf.keras.layers.Dropout(0.5)(x)

        encoder_output = tf.keras.layers.Dense(LATENT_DIM)(x)

        encoder = tf.keras.Model(encoder_input, encoder_output, name='encoder')

        x = tf.keras.layers.Dense(
            hidden_dims[-1], activation='relu')(encoder_output)
        for d in hidden_dims[-2::-1]:
            x = tf.keras.layers.Dense(d)(x)
            x = tf.keras.layers.BatchNormalization()(x)
            x = tf.keras.layers.Activation('relu')(x)
            x = tf.keras.layers.Dropout(0.5)(x)
        decoder_output = tf.keras.layers.Dense(input_shape, activation='relu')(x)
        autoencoder = tf.keras.Model(
            encoder_input, decoder_output, name='autoencoder')

        autoencoder.add_loss(
            cust_loss(encoder_input, encoder_output, decoder_output, LATENT_DIM))

        autoencoder.compile(optimizer='adam')
        return autoencoder

hypermodel = MyHyperModel()
tuner = kerastuner.tuners.hyperband.Hyperband(
    hypermodel,
    # tune_new_entries=False,
    # allow_new_entries=False,
    objective='val_loss',
    max_epochs=max_epochs,
    directory='keras-tuner',
    
    project_name='infoVAE_'+datetime.datetime.now().strftime("%Y%m%d-%H%M"))

tuner.search(data.values,
            epochs = max_epochs,
            validation_split=0.2,
     
```       batch_size = batch_size)



`[Trial complete]
[Trial summary]
 > Hp values:
 |-gaussian_noise: 0.05666365603069349
 |-latent_dim: 8
 |-n_layers: 3
 |-tuner/bracket: 2
 |-tuner/epochs: 2
 |-tuner/initial_epoch: 0
 |-tuner/round: 0
 |-units_layer_0: 29
 |-units_layer_1: 4
 |-units_layer_2: 9
 |-Score: 0.08588689330775859
 |-Best step: 0
Traceback (most recent call last):
  File "c:/Users/BMenthiere/Documents/TT/v2/infoVAE.py", line 119, in <module>
    batch_size = batch_size)
  File "C:\Users\BMenthiere\AppData\Local\Continuum\anaconda3\envs\TT\lib\site-packages\kerastuner\engine\base_tuner.py", line 112, in search
    trial = self.oracle.create_trial(self.tuner_id)
  File "C:\Users\BMenthiere\AppData\Local\Continuum\anaconda3\envs\TT\lib\site-packages\kerastuner\engine\oracle.py", line 149, in create_trial
    response = self._populate_space(trial_id)
  File "C:\Users\BMenthiere\AppData\Local\Continuum\anaconda3\envs\TT\lib\site-packages\kerastuner\tuners\hyperband.py", line 134, in _populate_space
    return self._random_trial(trial_id, bracket)
  File "C:\Users\BMenthiere\AppData\Local\Continuum\anaconda3\envs\TT\lib\site-packages\kerastuner\tuners\hyperband.py", line 215, in _random_trial
    values = self._random_values()
  File "C:\Users\BMenthiere\AppData\Local\Continuum\anaconda3\envs\TT\lib\site-packages\kerastuner\tuners\hyperband.py", line 266, in _random_values
    values[p.name] = p.random_sample(self._seed_state)
  File "C:\Users\BMenthiere\AppData\Local\Continuum\anaconda3\envs\TT\lib\site-packages\kerastuner\engine\hyperparameters.py", line 241, in random_sample
    return cumulative_prob_to_value(prob, self)
  File "C:\Users\BMenthiere\AppData\Local\Continuum\anaconda3\envs\TT\lib\site-packages\kerastuner\engine\hyperparameters.py", line 859, in cumulative_prob_to_value
    closest_index = np.abs(values - value).argmin()
ValueError: attempt to get argmin of an empty sequence`

**Comment by omalleyt12** [comment]
@bensdm Thanks for the issue!

Looking at the code, I think the issue is that some search spaces are being created with the values of other search spaces. This is probably not doing what you want, since search spaces are frozen after the first time they are defined

I.e. instead of:

```python
a = hp.Int('a', 0, 10)
b = hp.Int('b', 0, a)
```

do:

```
a = hp.Int('a', 0, 10)
b = hp.Int('b', 0, 10)
```

**Comment by rjavierch** [comment]
> @bensdm Thanks for the issue!
> 
> Looking at the code, I think the issue is that some search spaces are being created with the values of other search spaces. This is probably not doing what you want, since search spaces are frozen after the first time they are defined
> 
> I.e. instead of:
> 
> ```python
> a = hp.Int('a', 0, 10)
> # Defines the search space using the value of a the first time it is called
> b = hp.Int('b', 0, a) 
> ```
> 
> do:
> 
> ```python
> a = hp.Int('a', 0, 10)
> b = hp.Int('b', 0, 10)
> ```
> 
> or if you need a conditional search space, you can do:
> 
> ```python
> a = hp.Int('a', 0, 10)
> # Will create 10 different "b" hyperparameters, keyed off the value of "a"
> with hp.conditional_scope('a', a):
>   b = hp.Int('b', 0, a)
> ```
> 
> Please let me know if this fixes your issue

Unfortunately this is not working to me as in here  [Conditional Hyperparameters Not Displayed in TensorBoard for First Occurrence #692](https://github.com/keras-team/keras-tuner/issues/692). In my case, my hyperparameter `b` is always the lower boundary and it is not registered in the keras tuner summary.
