### ISSUE TITLE
Index out of range for Choice hyper param

### ISSUE THREAD

**Issue by yogi-dmt** [keras-team/keras-tuner#213]
In the hyperparameters.py module there is an error

```
def cumulative_prob_to_value(prob, hp):
    if isinstance(hp, Fixed):
        return hp.value
    elif isinstance(hp, Boolean):
        return bool(prob >= 0.5)
    elif isinstance(hp, Choice):
        ele_prob = 1 / len(hp.values)
        index = math.floor(prob / ele_prob)
        #at this line of code it is possible that the index is greater than the length of hp.values - 1 throwing an index of out bounds error
        return hp.values[index]
```

I'm not sure how to create a min reproducible scenario.

**Comment by omalleyt12** [comment]
@yogi-dmt Thanks for the issue!

I think this is fixed in the latest minor release, the line here should take care of it: 

https://github.com/keras-team/keras-tuner/blob/master/kerastuner/engine/hyperparameters.py#L1001

Could you please confirm and reopen if it's still an issue?

**Comment by david-thrower** [comment]
I hope I am explaining this clearly and concisely enough...

When running a tuner task within the scope of tf.distribute.MirroredStrategy, I am getting the same issue:

It tries to pick the 1800th item on a list of only 1136 items...  

My distributed strategy setup:

```python3
{ 
tf.keras.backend.clear_session()
strategy = tf.distribute.MirroredStrategy(
                                          devices=None,
                                          cross_device_ops=None)
{
```

Within my hypermodel function:

```python3
{ 
       # ...
       print(valid_permutations_df) # -> [1136 rows x 6 columns] 
       list_to_choose_item_option_from =\
            [int(i) for i in np.arange(valid_blocks_df.shape[0])] # Integer array of indexes  # ... (1136 items)
        blocks_index_chosen = hp.Choice(
                    name='blocks',
                    values=list_to_choose_blocks_option_from,
                    ordered=True)
        
        
        self.blocks = valid_permutations_df.loc[blocks_index_chosen]['blocks']
        print(self.blocks)
}
```
... My training task:

```python3
{

date = pendulum.now().__str__()[:16].replace("T","_").replace(":","_")

RESULTS_DIR = f'residualMLP_model_{date}'
PATIENCE = 10
PATIENCE_MIN_DELTA = 0.00001
BATCH_SIZE = 300
EPOCHS = 100

logdir = os.path.join("logs", RESULTS_DIR + "_TB")
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)

tuner = kt.Hyperband(
    model_builder.build_auto_residual_mlp,
    distribution_strategy = strategy,
    objective='val_loss',
    max_epochs = 30,
    hyperband_iterations = 2)
}
```

This prints on the console:

```
{

...
[1136 rows x 6 columns] # There are only 1136 items in np.arange(1136)
...

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/range.py", line 385, in get_loc
    return self._range.index(new_key)
ValueError: 1980 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/keras_tuner/engine/tuner.py", line 170, in _try_build
    model = self._build_hypermodel(hp)
  File "/usr/local/lib/python3.8/dist-packages/keras_tuner/engine/tuner.py", line 158, in _build_hypermodel
    model = self.hypermodel.build(hp)
  File "/notebooks/2022-01-27_NAS_Tests/residual_MLP_Tests/use-examples/Neural-Architecture-Search-Example/residualmlp/residual_mlp.py", line 387, in build_auto_residual_mlp
    self.blocks = valid_permutations_df.loc[blocks_index_chosen]['blocks']     # The number 1980 chosen 
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py", line 1202, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py", line 1153, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 3876, in xs
    loc = index.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/range.py", line 387, in get_loc
    raise KeyError(key) from err
KeyError: 1980     # It appears that kt chose 1980 from a list having 1136 as a maximum number.
}
```
