### ISSUE TITLE
max_trials not stopping after search space is exhausted

### ISSUE THREAD

**Issue by letmaik** [keras-team/keras-tuner#237]
If I set `max_trials=100` but my search space has only possible two configurations, then after running the two trials the tuner continues and tries to build a model with empty hyperparameters, which then fails with the usual "ValueError: Unknown parameter: ...".

**Comment by omalleyt12** [comment]
@letmaik Thanks for the issue! 

Can you provide a minimal example that reproduces the issue?

**Comment by letmaik** [comment]
This does NOT happen with the random and Hyperband tuners, only with the Bayesian tuner.

Simply define a bunch of hyperparameters which are all `Fixed` and then after the first trial you will get a bunch of this:
```
Traceback (most recent call last):
  ...
  File "/data/miniconda3/lib/python3.7/site-packages/kerastuner/engine/hyperparameters.py", line 617, in get
    'Unknown parameter: {}'.format(full_name))
ValueError: Unknown parameter: hidden_size
[Warning] Invalid model 0/5
```

and then eventually:
```
...
  File "/data/miniconda3/lib/python3.7/site-packages/kerastuner/engine/base_tuner.py", line 130, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/data/miniconda3/lib/python3.7/site-packages/kerastuner/engine/multi_execution_tuner.py", line 95, in run_trial
    model = self.hypermodel.build(trial.hyperparameters)
  File "/data/miniconda3/lib/python3.7/site-packages/kerastuner/engine/hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/data/miniconda3/lib/python3.7/site-packages/kerastuner/engine/hypermodel.py", line 115, in build
    'Too many failed attempts to build model.')
RuntimeError: Too many failed attempts to build model.
```

This is bad as all results are kind of lost then.
