### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'input_dim' and 'output_dim' when trying to use Randomsearch tuner

### ISSUE THREAD

**Issue by krs-github16** [keras-team/keras-tuner#260]
def build_model(hp):
    
    model = keras.Sequential([
        
        keras.layers.Embedding(vocab_size=hp.Int('vocab_size',
                                        min_value=150000,
                                        max_value=225000,
                                        step=25000),
                                  
                                  embedding_dim=hp.Int('embedding_dim',
                                        min_value=8,
                                        max_value=64,
                                        step=8),
                                  
                                  input_length=max_length),
        
        keras.layers.GlobalAveragePooling1D(),
        
        keras.layers.Dense(units=hp.Int('dense_1_units',
                                        min_value=8,
                                        max_value=32,
                                        step=8),
                              
                              kernel_regularizer=keras.regularizers.l2(hp.Choice('regularizer_value',
                                                                          values=[1e-1, 1e-2, 1e-3])),
                              activation='relu'),
        
        keras.layers.Dropout(hp.Choice('drop_out_1_value',
                                          values=[0.1,0.2,0.3]),
                                          seed=random_seed),
        
        keras.layers.Dense(3,activation='softmax')
    ])
    
    
    model.compile(optimizer=keras.optimizers.Adam(learning_rate=hp.Choice('learning_rate',
                                                                  values=[1e-1, 1e-2, 1e-3])),
                    loss='categorical_crossentropy',

                    metrics=['accuracy'])

    return model

tuner=RandomSearch(build_model,
                  objective='val_loss',
                  max_trials=5,
                  executions_per_trial=3,
                  directory='my_keras_tuner_dir',
                  project_name='news_sentiment')

Traceback (most recent call last):
  File "C:\Users\krajasekhara\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "<ipython-input-58-22abd649ed4e>", line 15, in build_model
    input_length=max_length),
TypeError: __init__() missing 2 required positional arguments: 'input_dim' and 'output_dim'
[Warning] Invalid model 0/5
Traceback (most recent call last):
  File "C:\Users\krajasekhara\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "<ipython-input-58-22abd649ed4e>", line 15, in build_model
    input_length=max_length),
TypeError: __init__() missing 2 required positional arguments: 'input_dim' and 'output_dim'
[Warning] Invalid model 1/5
Traceback (most recent call last):
  File "C:\Users\krajasekhara\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "<ipython-input-58-22abd649ed4e>", line 15, in build_model
    input_length=max_length),
TypeError: __init__() missing 2 required positional arguments: 'input_dim' and 'output_dim'
[Warning] Invalid model 2/5
Traceback (most recent call last):
  File "C:\Users\krajasekhara\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "<ipython-input-58-22abd649ed4e>", line 15, in build_model
    input_length=max_length),
TypeError: __init__() missing 2 required positional arguments: 'input_dim' and 'output_dim'
[Warning] Invalid model 3/5
Traceback (most recent call last):
  File "C:\Users\krajasekhara\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "<ipython-input-58-22abd649ed4e>", line 15, in build_model
    input_length=max_length),
TypeError: __init__() missing 2 required positional arguments: 'input_dim' and 'output_dim'
[Warning] Invalid model 4/5
Traceback (most recent call last):
  File "C:\Users\krajasekhara\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "<ipython-input-58-22abd649ed4e>", line 15, in build_model
    input_length=max_length),
TypeError: __init__() missing 2 required positional arguments: 'input_dim' and 'output_dim'
[Warning] Invalid model 5/5
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\hypermodel.py in build(self, hp)
    104                 with maybe_distribute(self.distribution_strategy):
--> 105                     model = self.hypermodel.build(hp)
    106             except:

<ipython-input-58-22abd649ed4e> in build_model(hp)
     14 
---> 15                                   input_length=max_length),
     16 

TypeError: __init__() missing 2 required positional arguments: 'input_dim' and 'output_dim'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-61-5543d79495f7> in <module>
      4                   executions_per_trial=3,
      5                   directory='my_keras_tuner_dir',
----> 6                   project_name='news_sentiment')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\tuners\randomsearch.py in __init__(self, hypermodel, objective, max_trials, seed, hyperparameters, tune_new_entries, allow_new_entries, **kwargs)
    173             oracle,
    174             hypermodel,
--> 175             **kwargs)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\multi_execution_tuner.py in __init__(self, oracle, hypermodel, executions_per_trial, **kwargs)
     56                  **kwargs):
     57         super(MultiExecutionTuner, self).__init__(
---> 58             oracle, hypermodel, **kwargs)
     59         if isinstance(oracle.objective, list):
     60             raise ValueError(

~\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\tuner.py in __init__(self, oracle, hypermodel, max_model_size, optimizer, loss, metrics, distribution_strategy, directory, project_name, logger, tuner_id, overwrite)
    101                                     project_name=project_name,
    102                                     logger=logger,
--> 103                                     overwrite=overwrite)
    104 
    105         self.distribution_strategy = distribution_strategy

~\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\base_tuner.py in __init__(self, oracle, hypermodel, directory, project_name, logger, overwrite)
     89         self._display = tuner_utils.Display()
     90 
---> 91         self._populate_initial_space()
     92 
     93         if not overwrite and tf.io.gfile.exists(self._get_tuner_fname()):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\base_tuner.py in _populate_initial_space(self)
    104         """
    105         hp = self.oracle.get_space()
--> 106         self.hypermodel.build(hp)
    107         self.oracle.update_space(hp)
    108 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\hypermodel.py in _build_wrapper(self, hp, *args, **kwargs)
     63             # to the search space.
     64             hp = hp.copy()
---> 65         return self._build(hp, *args, **kwargs)
     66 
     67 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\kerastuner\engine\hypermodel.py in build(self, hp)
    113                 if i == self._max_fail_streak:
    114                     raise RuntimeError(
--> 115                         'Too many failed attempts to build model.')
    116                 continue
    117 

RuntimeError: Too many failed attempts to build model.

**Comment by Erik-BM** [comment]
See https://keras.io/layers/embeddings/ . Args are input_dim and output_dim, not vocab_size and embedding_dim.

**Comment by krs-github16** [comment]
U can close the issue. I'm extremely sorry for being careless.
But I ran few epochs with vocab_size and embedding_dim as arguments to build a baseline model.
Don't know why these arguments don't work during tuning.
