### ISSUE TITLE
InactiveRpcError: XA and XB must have the same number of columns

### ISSUE THREAD

**Issue by Astlaan** [keras-team/keras-tuner#332]
Hello,

So, I'm using keras tuner in a Distributed tuning fashion (trials divided among several worker nodes).

I left a chief + 8 worker nodes working overnight. However, after working properly for several hours,  5 of the worker nodes crashed, with the following output.

```
Epoch 102/1000
50/50 [==============================] - 18s 356ms/step - loss: 0.0634 - mse: 1.7068e-05 - val_loss: 0.0630 - val_mse: 1.7067e-05
Epoch 103/1000
50/50 [==============================] - 18s 359ms/step - loss: 0.0634 - mse: 1.6974e-05 - val_loss: 0.0637 - val_mse: 4.3100e-05
[Trial complete]
[Trial summary]
 |-Trial ID: d1e18e324bfd74349cfc54694ff929aa
 |-Score: 0.06294629722833633
 |-Best step: 0
 > Hyperparameters:
 |-num_layers_embedding: 1
 |-num_layers_hidden: 1
 |-num_layers_rnn: 2
 |-unitsembedding_0: 4
 |-unitsembedding_1: 8
 |-unitshidden_0: 16
 |-unitsrnn_0: 16
Traceback (most recent call last):
  File "run_keras_tuner_specific.py", line 573, in <module>
    start(args.database, args.maxdepth, args.pname, args.max_trials, args.batch_size)
  File "run_keras_tuner_specific.py", line 542, in start
    validation_data=(x_val, y_val), callbacks = [EarlyStopping(monitor='val_loss', patience=20)])
  File "/home/dmalvalada/bulk/home/dmalvalada/bulk/miniconda3/envs/tensorflow/lib/python3.7/site-packages/kerastuner/engine/base_tuner.py", line 120, in search
    trial = self.oracle.create_trial(self.tuner_id)
  File "/home/dmalvalada/bulk/home/dmalvalada/bulk/miniconda3/envs/tensorflow/lib/python3.7/site-packages/kerastuner/distribute/oracle_client.py", line 60, in create_trial
    tuner_id=tuner_id), wait_for_ready=True)
  File "/home/dmalvalada/bulk/home/dmalvalada/bulk/miniconda3/envs/tensorflow/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/dmalvalada/bulk/home/dmalvalada/bulk/miniconda3/envs/tensorflow/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: XA and XB must have the same number of columns (i.e. feature dimension.)"
        debug_error_string = "{"created":"@1592870116.676780583","description":"Error received from peer ipv4:10.0.106.31:8894","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Exception calling application: XA and XB must have the same number of columns (i.e. feature dimension.)","grpc_status":2}"
>
```

Any idea?

**Comment by yixingfu** [comment]
Are you using Bayesian tuner?

**Comment by Astlaan** [comment]
Yes I am!

**Comment by yixingfu** [comment]
Then it is certainly a GPR regression problem. I am guessing something goes on with saving and reading previous trials. Let me try to reproduce and see what is going on. 

Meanwhile I see an interesting comment on another issue (https://github.com/keras-team/keras-tuner/issues/331#issuecomment-647736586). So perhaps trying RandomSearch is not too bad an idea for the moment.
