### ISSUE TITLE
Unable to upgrade keras tuner to 1.0.2

### ISSUE THREAD

**Issue by robert-hoyt** [keras-team/keras-tuner#336]
I am attempting to try AutoKeras. I have it and TensorFlow installed, using a Jupyter Lab on my Mac. First, it told me keras tuner was not installed. I installed it successfully with pip install keras-tuner (version 1.0.1). When I run this code import autokeras as ak
model = ak.ImageClassifier(max_trial = 100) it says I don't have the most recent version of keras tuner so directs me to
the command pip install git+https://github.com/keras-team/keras-tuner.git@1.0.2rc0#egg=keras-tuner-1.0.2rc0. This begins the install but then says requirement already satisfied so I can not proceed. Error message below

Collecting keras-tuner-1.0.2rc0 from git+https://github.com/keras-team/keras-tuner.git@1.0.2rc0#egg=keras-tuner-1.0.2rc0
  Cloning https://github.com/keras-team/keras-tuner.git (to revision 1.0.2rc0) to /private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-install-0_kh3j9a/keras-tuner-1.0.2rc0
  Running command git clone -q https://github.com/keras-team/keras-tuner.git /private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-install-0_kh3j9a/keras-tuner-1.0.2rc0
  Running command git checkout -q 5d16a5a9cd883fe6366d523a5e59b72cfefb7f77
  WARNING: Generating metadata for package keras-tuner-1.0.2rc0 produced metadata for project name keras-tuner. Fix your #egg=keras-tuner-1.0.2rc0 fragments.
Requirement already satisfied (use --upgrade to upgrade): keras-tuner from git+https://github.com/keras-team/keras-tuner.git@1.0.2rc0#egg=keras-tuner-1.0.2rc0 in /Applications/anaconda3/lib/python3.7/site-packages
Requirement already satisfied: packaging in /Applications/anaconda3/lib/python3.7/site-packages (from keras-tuner) (19.2)
Requirement already satisfied: future in /Applications/anaconda3/lib/python3.7/site-packages (from keras-tuner) (0.17.1)
Requirement already satisfied: numpy in /Applications/anaconda3/lib/python3.7/site-packages (from keras-tuner) (1.17.2)
Requirement already satisfied: tabulate in /Applications/anaconda3/lib/python3.7/site-packages (from keras-tuner) (0.8.7)
Requirement already satisfied: terminaltables in /Applications/anaconda3/lib/python3.7/site-packages (from keras-tuner) (3.1.0)
Requirement already satisfied: colorama in /Applications/anaconda3/lib/python3.7/site-packages (from keras-tuner) (0.4.1)
Requirement already satisfied: tqdm in /Applications/anaconda3/lib/python3.7/site-packages (from keras-tuner) (4.36.1)
Requirement already satisfied: requests in /Applications/anaconda3/lib/python3.7/site-packages (from keras-tuner) (2.22.0)
Requirement already satisfied: scipy in /Applications/anaconda3/lib/python3.7/site-packages (from keras-tuner) (1.4.1)
Requirement already satisfied: scikit-learn in /Applications/anaconda3/lib/python3.7/site-packages (from keras-tuner) (0.22)
Requirement already satisfied: six in /Applications/anaconda3/lib/python3.7/site-packages (from packaging->keras-tuner) (1.12.0)
Requirement already satisfied: pyparsing>=2.0.2 in /Applications/anaconda3/lib/python3.7/site-packages (from packaging->keras-tuner) (2.4.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Applications/anaconda3/lib/python3.7/site-packages (from requests->keras-tuner) (1.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Applications/anaconda3/lib/python3.7/site-packages (from requests->keras-tuner) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Applications/anaconda3/lib/python3.7/site-packages (from requests->keras-tuner) (2019.9.11)
Requirement already satisfied: idna<2.9,>=2.5 in /Applications/anaconda3/lib/python3.7/site-packages (from requests->keras-tuner) (2.8)
Requirement already satisfied: joblib>=0.11 in /Applications/anaconda3/lib/python3.7/site-packages (from scikit-learn->keras-tuner) (0.13.2)
Building wheels for collected packages: keras-tuner, keras-tuner
  Building wheel for keras-tuner (setup.py) ... done
  Created wheel for keras-tuner: filename=keras_tuner-1.0.2rc0-cp37-none-any.whl size=89059 sha256=1339bf79aec5df16acb5e0762b7ff3aa1b834c0d4021c5b0d4cc1f5aa79b7de4
  Stored in directory: /private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-ephem-wheel-cache-ujgjaue3/wheels/ab/97/20/917008aafbd47b823fb0bc43989739b1195c682036641a49d7
  Building wheel for keras-tuner (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Applications/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-install-0_kh3j9a/keras-tuner/setup.py'"'"'; __file__='"'"'/private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-install-0_kh3j9a/keras-tuner/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-wheel-1ty5n8w6 --python-tag cp37
       cwd: /private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-install-0_kh3j9a/keras-tuner/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Applications/anaconda3/lib/python3.7/tokenize.py", line 447, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-install-0_kh3j9a/keras-tuner/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for keras-tuner
  Running setup.py clean for keras-tuner
  ERROR: Command errored out with exit status 1:
   command: /Applications/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-install-0_kh3j9a/keras-tuner/setup.py'"'"'; __file__='"'"'/private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-install-0_kh3j9a/keras-tuner/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-install-0_kh3j9a/keras-tuner
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Applications/anaconda3/lib/python3.7/tokenize.py", line 447, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/4c/zjb0c1753g70dgrrsb3xy6c80000gn/T/pip-install-0_kh3j9a/keras-tuner/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for keras-tuner
Successfully built keras-tuner
Failed to build keras-tuner
Note: you may need to restart the kernel to use updated packages.

**Comment by robert-hoyt** [comment]
I decided to use the exact Python code the AutoKeras website used and to use CoLab, instead of a Jupyter Lab. I was able to start an analysis so this issue is closed.
