### ISSUE TITLE
Error when using conditional_scope

### ISSUE THREAD

**Issue by sim-san** [keras-team/keras-tuner#341]
I using the Hyperband-Tuner and create multiple tuner with the joblib on one computer. I want to try the new conditional_scope (https://github.com/keras-team/keras-tuner/pull/242). 

```
model = Sequential()
model.add(layers.Flatten())

min_layers = 2
max_layers = 4
for layer_idx in range(hp.Int('num_layers', min_layers, max_layers, default=max_layers)):
    with hp.conditional_scope('num_layers', list(range(layer_idx + 1, max_layers + 1))):
        units = hp.Int(f'units_{layer_idx}', min_value=64, max_value=256, step=32)
        model.add(dense_layer(units=units, activation=activation))

        # dropout = hp.Fixed(f'dropout_{layer_idx}', value=0.3) => creating an error
        # dropout = hp.Float(f'dropout_{layer_idx}', min_value=0.1, max_value=0.4, step=0.1)  => creating an error
        dropout = hp.Choice(f'dropout_{layer_idx}', [0.2, 0.3, 0.4])
        
        model.add(layers.Dropout(rate=dropout))
```

But with the hp.Fixed and hp.Float after the 'conditional_scope', I get the following error. So I have to use the hp.Choice.

```
Traceback (most recent call last):
  File "/home/sander/src/keras-tuner/kerastuner/engine/hypermodel.py", line 104, in build
    model = self.hypermodel.build(hp)
Traceback (most recent call last):
  File "/home/sander/src/keras-tuner/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/home/sander/PyCharmProjects/optimization_library/optimization_library/models.py", line 86, in build
    dropout = hp.Fixed(f'dropout_{layer_idx}', value=0.3)
Traceback (most recent call last):
  File "/home/sander/src/keras-tuner/kerastuner/engine/hypermodel.py", line 104, in build
    model = self.hypermodel.build(hp)
  File "/home/sander/src/keras-tuner/kerastuner/engine/hyperparameters.py", line 837, in Fixed
    return self._retrieve(hp)
  File "/home/sander/src/keras-tuner/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/home/sander/src/keras-tuner/kerastuner/engine/hyperparameters.py", line 625, in _retrieve
    return self.values[hp.name]
  File "/home/sander/PyCharmProjects/optimization_library/optimization_library/models.py", line 86, in build
    dropout = hp.Fixed(f'dropout_{layer_idx}', value=0.3)
  File "/home/sander/src/keras-tuner/kerastuner/engine/hyperparameters.py", line 837, in Fixed
    return self._retrieve(hp)
  File "/home/sander/src/keras-tuner/kerastuner/engine/hypermodel.py", line 104, in build
    model = self.hypermodel.build(hp)
KeyError: 'dropout_0'
  File "/home/sander/src/keras-tuner/kerastuner/engine/hyperparameters.py", line 625, in _retrieve
    return self.values[hp.name]
  File "/home/sander/src/keras-tuner/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/home/sander/PyCharmProjects/optimization_library/optimization_library/models.py", line 86, in build
    dropout = hp.Fixed(f'dropout_{layer_idx}', value=0.3)
```

Do I make a mistake ?
Can you give me a hint ?

**Comment by yixingfu** [comment]
Could you try master branch? I am unable to reproduce the problem. Maybe it is fixed by some more recent change (including one I know that made Fixed more consistent with other hps).

If the error persist, can you also include the part of your code that defines tuner?

**Comment by yixingfu** [comment]
Also I am not sure if it is related to the fact you tried to parallelize keras-tuner.  Does the problem come up when you run a single process?  If not can you provide a bit more detail on how you were using joblib?
