### ISSUE TITLE
AttributeError: 'HyperParameters' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by trulicup** [keras-team/keras-tuner#435]
```python
def model_builder(hp):
  model = keras.Sequential()
  
  model.add(keras.Input(shape=(train_features.shape[-1],)))
  model.add(keras.layers.BatchNormalization())

  hp_units = hp.Int('units', min_value = 32, max_value = 512, step = 32)

  model.add(keras.layers.Dense(units = hp_units, activation = 'relu'))
  model.add(keras.layers.Dense(units = hp_units, activation = 'relu'))
  model.add(keras.layers.Dense(units = hp_units, activation = 'relu'))
  model.add(keras.layers.Dropout(0.3))

  model.add(keras.layers.Dense(1, activation="softmax"))

  hp_learning_rate = hp.Choice('learning_rate', values = [1e-2, 1e-3, 1e-4]) 

  model.compile(optimizer = keras.optimizers.Adam(learning_rate = hp_learning_rate),
                loss = keras.losses.SparseCategoricalCrossentropy(), 
                metrics = ['accuracy'])
  
  return model
````

```python
tuner = kt.Hyperband(model,
                     objective = 'val_accuracy', 
                     max_epochs = 5,
                     factor = 3,
                     directory = 'my_dir',
                     project_name = 'sars_epitone_region_classifier',
                     seed=20)
```

train_features info:
> <class 'pandas.core.frame.DataFrame'>
> Int64Index: 14387 entries, 7321 to 10714
> Data columns Total: 11
> dtypes: float64(9), int64(2)

### Traceback (most recent call last):

>   File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 105, in build
>     model = self.hypermodel.build(hp)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
>     outputs = call_fn(inputs, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py", line 372, in call
>     return super(Sequential, self).call(inputs, training=training, mask=mask)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 386, in call
>     inputs, training=training, mask=mask)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 508, in _run_internal_graph
>     outputs = node.layer(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
>     outputs = call_fn(inputs, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py", line 727, in call
>     inputs_dtype = inputs.dtype.base_dtype

  AttributeError: **'HyperParameters' object has no attribute 'dtype'**

I'm trying to hypertune a binary classifier model, but i cant get pass this error. I've tried everything that i could think of with no luck.

**Comment by trulicup** [comment]
```python
tuner = kt.Hyperband(model, ...)
```
to 
```python
tuner = kt.Hyperband(model_builder, ...)
```
fixed the issue...
