### ISSUE TITLE
Unable to serialize/export/convert a KT trained model to ONNX

### ISSUE THREAD

**Issue by deakkon** [keras-team/keras-tuner#458]
Hi everyone, 

I am having some difficulties converting/exporting a KT-optimized model to ONNX. 

The model, when trained normally (i.e. with manually set hyperparams and without the use of KT) serialized without issues (and load on the target architecture). 

When I try to optimize it with KT, although there are no issues during training, I can not serialize the model. I tried on Py 3.8 with:
1. KT 1.0.1 + TF 2.2 and 
2. KT 1.0.2 and TF 2.3.1

Neither of them works out of the box. The error message I am getting: 

_ValueError: Model <tensorflow.python.keras.saving.saved_model.load.VAE object at 0x7fe1142b2610> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling `.fit()` or `.predict()`. To manually set the shapes, call `model.build(input_shape)`._

Find the relevant code below. Any help would be greatly appreciated. 

## MODEL ##

class Sampling(Layer):

    """Uses (z_mean, z_log_var) to sample z, the vector encoding a digit."""

    def call(self, inputs, **kwargs):
        z_mean, z_log_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

class Encoder(Layer):

    """Maps input to a triplet (z_mean, z_log_var, z)."""

    def __init__(self, latent_dim, name="encoder", hp=None, **kwargs):
        super(Encoder, self).__init__(name=name, **kwargs)

        self.dense_proj_1 = Dense(units=hp.Int("decoder_dense_proj_1",
                                               2048, 5096, 256),
                                  activation="tanh")
        self.drop_1 = Dropout(
            hp.Float("decoder_droput_1", min_value=0.0, max_value=0.5, step=0.1)
        )

        self.dense_proj_2 = Dense(
            units=hp.Int("decoder_dense_proj_2", 512, 2048, 256),
            activation="tanh"
        )
        self.drop_2 = Dropout(
            hp.Float("decoder_droput_2", min_value=0.0, max_value=0.5, step=0.1)
        )

        self.dense_mean = Dense(latent_dim)
        self.dense_log_var = Dense(latent_dim)
        self.sampling = Sampling()

class Decoder(Layer):
    """Converts z, the encoded digit vector, back into input."""

    def __init__(self, original_dim=None, name="decoder", hp=None, **kwargs):
        super(Decoder, self).__init__(name=name, **kwargs)
        self.dense_proj_1 = Dense(
            units=hp.Int("decoder_dense_proj_1", 512, 2048, 256),
            activation="tanh"
        )
        self.drop_1 = Dropout(
            hp.Float("decoder_droput_1", min_value=0.0, max_value=0.5, step=0.1)
        )

        self.dense_proj_2 = Dense(units=hp.Int("decoder_dense_proj_2",
                                               2048, 5096, 256),
                                  activation="tanh")
        self.drop_2 = Dropout(
            hp.Float("decoder_droput_2", min_value=0.0, max_value=0.5, step=0.1)
        )
        self.dense_output = Dense(original_dim, activation="sigmoid", name="decoder_output")

    def call(self, inputs, **kwargs):
        x = self.dense_proj_1(inputs)
        x = self.drop_1(x)
        x = self.dense_proj_2(x)
        x = self.drop_2(x)
        return self.dense_output(x)

class VAE(Model):

    def __init__(self, input_shape, latent_dim=None, hp=None, **kwargs):
        super(VAE, self).__init__(**kwargs)
        if not latent_dim:
            latent_dim = hp.Int("latent_dim", 100, 400, 100)
        self.model_input = Input(shape=input_shape)
        self.encoder = Encoder(latent_dim, hp=hp)
        self.decoder = Decoder(original_dim=input_shape, hp=hp)

    def call(self, inputs, **kwargs):
        z_mean, z_log_var, z = self.encoder(inputs)
        reconstructed = self.decoder(z)

        # Add KL divergence regularization loss.
        kl_loss = -0.5 * tf.reduce_mean(
            z_log_var - tf.square(z_mean) - tf.exp(z_log_var) + 1
        )
        self.add_loss(kl_loss)
        return reconstructed

def build_model(hp):

    input_shape=9487 # I need to pass this to VAR as my input shapes change over time
    model = VAE(input_shape, hp=hp)
    model.compile(
        optimizer=Adam(
            hp.Choice('learning_rate',
                      values=[1e-2, 1e-3, 1e-4])),
        loss='mse'
    )
    return model

##    TRAIN MODEL     ##

date_time_stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

ktuner_logdir = "{}ktuner/".format(ROOT_DIR)

tuner = RandomSearch(
    hypermodel=build_model,
    objective=Objective("val_loss", direction="min"),
    max_trials=2,
    executions_per_trial=1,
    directory=ktuner_logdir,
    project_name="VAE_{}".format(date_time_stamp),
    overwrite=True,
    seed=42)

tuner.search(train_generator,
             validation_data=(val_generator),
             batch_size=batch_size,
             epochs=2,
             verbose=0,
             callbacks=[
                 tensorboard_callback,
                 reduce_lr,
                 stop_callback
             ],
             shuffle=True,
             )

## SERIALIZE MODEL AND CONVERT TO ONNX ##
####None of the approaches to convert, found online, are working. The try block doesn't serialize anything, while the except clause serializes the trained model to disk but doesn't convert the model to ONNX

try:
    best_model.save('trained_models/vae', save_format='tf')
    onnx_model = onnxmltools.convert_keras(best_model, target_opset=9)
    onnxmltools.utils.save_model(onnx_model,
                             '{}trained_models/vae.onnx'.format(ROOT_DIR))
except ValueError:
    # best_model.save_weights('./trained_models/vae_weights', save_format='tf')
    tf.saved_model.save(best_model, './trained_models/save_model_v2')
    model = tf.keras.models.load_model('./trained_models/save_model_v2')
    onnx_model = onnxmltools.convert_keras(model, model.name)
    onnxmltools.save_model(onnx_model, './data/save_model_v2.onnx')

# FULL TRACEBACK
Traceback (most recent call last):
  File "src/trainers/VAETrainer.py", line 124, in <module>
    best_model.save('trained_models/vae', save_format='tf')
  File "/home/jurica.seva/miniconda3/envs/kp/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1978, in save
    save.save_model(self, filepath, overwrite, include_optimizer, save_format,
  File "/home/jurica.seva/miniconda3/envs/kp/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 133, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer,
  File "/home/jurica.seva/miniconda3/envs/kp/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 65, in save
    saving_utils.raise_model_input_error(model)
  File "/home/jurica.seva/miniconda3/envs/kp/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 93, in raise_model_input_error
    raise ValueError(
ValueError: Model <src.models.VAE.VAE object at 0x7fe183fc3fa0> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling `.fit()` or `.predict()`. To manually set the shapes, call `model.build(input_shape)`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/trainers/VAETrainer.py", line 132, in <module>
    onnx_model = onnxmltools.convert_keras(model, model.name)
  File "/home/jurica.seva/miniconda3/envs/kp/lib/python3.8/site-packages/onnxmltools/convert/main.py", line 33, in convert_keras
    return convert(model, name, doc_string, target_opset, channel_first_inputs)
  File "/home/jurica.seva/miniconda3/envs/kp/lib/python3.8/site-packages/keras2onnx/main.py", line 62, in convert_keras
    tf_graph = build_layer_output_from_model(model, output_dict, input_names, output_names)
  File "/home/jurica.seva/miniconda3/envs/kp/lib/python3.8/site-packages/keras2onnx/_parser_tf.py", line 302, in build_layer_output_from_model
    return extract_outputs_from_subclassing_model(model, output_dict, input_names, output_names)
  File "/home/jurica.seva/miniconda3/envs/kp/lib/python3.8/site-packages/keras2onnx/_parser_tf.py", line 258, in extract_outputs_from_subclassing_model
    function = _saving_utils.trace_model_call(model)
  File "/home/jurica.seva/miniconda3/envs/kp/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 122, in trace_model_call
    raise_model_input_error(model)
  File "/home/jurica.seva/miniconda3/envs/kp/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 93, in raise_model_input_error
    raise ValueError(
ValueError: Model <tensorflow.python.keras.saving.saved_model.load.VAE object at 0x7fe1142b2610> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling `.fit()` or `.predict()`. To manually set the shapes, call `model.build(input_shape)`.

**Comment by deakkon** [comment]
I found a workaround; calling fit on the best_model for 1 epoch makes it serializable.
