### ISSUE TITLE
HyperResNet fails to build

### ISSUE THREAD

**Issue by abhishekthanki** [keras-team/keras-tuner#473]
Hello,

I was checking out keras tuner and was looking into using it for fine-tuning ResNet but I can into a error. Here is the Keras tuner code:

```
from kerastuner.applications import HyperResNet
from kerastuner.tuners import Hyperband

hypermodel = HyperResNet(input_shape=(224, 224, 3), classes=config.CLASSES)
tuner = Hyperband(hypermodel, objective="val_accuracy", max_epochs=40,
	directory="models", project_name="camo", seed=42)
```

**I'm getting the following error:** 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 104, in build
    model = self.hypermodel.build(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/applications/resnet.py", line 128, in build
    self.classes, activation='softmax', name='probs')(x)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py", line 1160, in __init__
    self.units = int(units) if not isinstance(units, int) else units
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

Invalid model 3/5

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 104, in build
    model = self.hypermodel.build(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/applications/resnet.py", line 128, in build
    self.classes, activation='softmax', name='probs')(x)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py", line 1160, in __init__
    self.units = int(units) if not isinstance(units, int) else units
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

Invalid model 4/5
Invalid model 5/5

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 104, in build
    model = self.hypermodel.build(hp)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/applications/resnet.py", line 128, in build
    self.classes, activation='softmax', name='probs')(x)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py", line 1160, in __init__
    self.units = int(units) if not isinstance(units, int) else units
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py in build(self, hp)
    103                 with maybe_distribute(self.distribution_strategy):
--> 104                     model = self.hypermodel.build(hp)
    105             except:

10 frames

/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py in _build_wrapper(self, hp, *args, **kwargs)
     63             hp = hp.copy()
---> 64         return self._build(hp, *args, **kwargs)
     65 

/usr/local/lib/python3.6/dist-packages/kerastuner/applications/resnet.py in build(self, hp)
    127             x = layers.Dense(
--> 128                 self.classes, activation='softmax', name='probs')(x)
    129             model = keras.Model(inputs, x, name='ResNet')

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py in __init__(self, units, activation, use_bias, kernel_initializer, bias_initializer, kernel_regularizer, bias_regularizer, activity_regularizer, kernel_constraint, bias_constraint, **kwargs)
   1159 
-> 1160     self.units = int(units) if not isinstance(units, int) else units
   1161     self.activation = activations.get(activation)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'


During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)

<ipython-input-36-c1859180e343> in <module>()
      1 tuner = Hyperband(hypermodel, objective="val_accuracy", max_epochs=40,
----> 2 	directory="models", project_name="camo", seed=42)

/usr/local/lib/python3.6/dist-packages/kerastuner/tuners/hyperband.py in __init__(self, hypermodel, objective, max_epochs, factor, hyperband_iterations, seed, hyperparameters, tune_new_entries, allow_new_entries, **kwargs)
    345             oracle=oracle,
    346             hypermodel=hypermodel,
--> 347             **kwargs)
    348 
    349     def run_trial(self, trial, *fit_args, **fit_kwargs):

/usr/local/lib/python3.6/dist-packages/kerastuner/engine/multi_execution_tuner.py in __init__(self, oracle, hypermodel, executions_per_trial, **kwargs)
     57                  **kwargs):
     58         super(MultiExecutionTuner, self).__init__(
---> 59             oracle, hypermodel, **kwargs)
     60         if isinstance(oracle.objective, list):
     61             raise ValueError(

/usr/local/lib/python3.6/dist-packages/kerastuner/engine/tuner.py in __init__(self, oracle, hypermodel, max_model_size, optimizer, loss, metrics, distribution_strategy, directory, project_name, logger, tuner_id, overwrite)
    103                                     project_name=project_name,
    104                                     logger=logger,
--> 105                                     overwrite=overwrite)
    106 
    107         self.distribution_strategy = distribution_strategy

/usr/local/lib/python3.6/dist-packages/kerastuner/engine/base_tuner.py in __init__(self, oracle, hypermodel, directory, project_name, logger, overwrite)
     88         self._display = tuner_utils.Display(oracle=self.oracle)
     89 
---> 90         self._populate_initial_space()
     91 
     92         if not overwrite and tf.io.gfile.exists(self._get_tuner_fname()):

/usr/local/lib/python3.6/dist-packages/kerastuner/engine/base_tuner.py in _populate_initial_space(self)
    103         """
    104         hp = self.oracle.get_space()
--> 105         self.hypermodel.build(hp)
    106         self.oracle.update_space(hp)
    107 

/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py in _build_wrapper(self, hp, *args, **kwargs)
     62             # to the search space.
     63             hp = hp.copy()
---> 64         return self._build(hp, *args, **kwargs)
     65 
     66 

/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hypermodel.py in build(self, hp)
    111                 if i == self._max_fail_streak:
    112                     raise RuntimeError(
--> 113                         'Too many failed attempts to build model.')
    114                 continue
    115 

RuntimeError: Too many failed attempts to build model.
```

I have tried TensorFlow 2.2 and 2.4 but I keep running into the same error with both versions. So, am I doing something wrong here? Please help!

Additionally, With TensorFlow 2.0, I run into an import error (w.r.t. TF) which leads me to think that keras-tuner is not compatbile with TF 2.0 and the documentation + GitHub page might need to be updated.

**Comment by DevloperHS** [comment]
The problem lies in this `classes=config.CLASSES)` - classes should be int as it is inferring you have returned classes from the `config file`. Btw what is CLASSES , ***int or str***

**Comment by haifeng-jin** [comment]
`classes` is an int indicating the number of classes for the classification task.
