### ISSUE TITLE
Can't import `keras_tuner`: AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

### ISSUE THREAD

**Issue by Mnaukal** [keras-team/keras-tuner#573]
Hi, I have a problem with importing `keras_tuner` version 1.0.3. It raises an AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'. (I use TF version 2.5.0.)

Traceback:
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\micha\AppData\Local\Programs\Python\Python37\lib\site-packages\keras_tuner\__init__.py", line 20, in <module>
    from . import oracles
  File "C:\Users\micha\AppData\Local\Programs\Python\Python37\lib\site-packages\keras_tuner\oracles\__init__.py", line 17, in <module>
    from ..tuners.bayesian import BayesianOptimizationOracle
  File "C:\Users\micha\AppData\Local\Programs\Python\Python37\lib\site-packages\keras_tuner\tuners\__init__.py", line 17, in <module>
    from .bayesian import BayesianOptimization
  File "C:\Users\micha\AppData\Local\Programs\Python\Python37\lib\site-packages\keras_tuner\tuners\bayesian.py", line 8, in <module>
    from ..engine import hyperparameters as hp_module
  File "C:\Users\micha\AppData\Local\Programs\Python\Python37\lib\site-packages\keras_tuner\engine\hyperparameters.py", line 29, in <module>
    from ..protos import keras_tuner_pb2
  File "C:\Users\micha\AppData\Local\Programs\Python\Python37\lib\site-packages\keras_tuner\protos\keras_tuner_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

When I downgraded to 1.0.2, it seems to import fine.

**Comment by haifeng-jin** [comment]
Hi @Mnaukal ,

Thanks for the issue.
I cannot reproduce this error.
Would you please share a colab notebook with me?

Thanks you!

**Comment by Mnaukal** [comment]
Hi, I cannot reproduce it in colab either. Sorry for that, it is then probably caused by some specific settings on my local system. I believe you can close this issue as we will not be able to tell which exact setting causes it.
