### ISSUE TITLE
TypeError using BayesianOptimization

### ISSUE THREAD

**Issue by codecypher** [keras-team/keras-tuner#671]
**Describe the bug**

My code works fine with RandomSearch but generates error using kt.BayesianOptimization, so not sure about the source of the error. The code was working fine in previous version of KerasTuner but the API changed so much in recent versions that I had to rewrite the code.

    tuner = kt.BayesianOptimization(
        hypermodel=build_model,
        hyperparameters=hp,
        objective=params.objective,
        max_trials=params.max_trials,
        executions_per_trial=5,
        # optimizer=keras.optimizers.Adam(params.lr),
        # loss=params.loss,
        # metrics=["sparse_categorical_crossentropy",],
        # tune_new_entries=False,  # prevent unlisted parameters from being tuned
        overwrite=True,
        directory=path_ckpt,
        project_name=project_name,
    )

Best val_loss So Far: 3021.8214111328125
Total elapsed time: 00h 20m 26s
Traceback (most recent call last):
  File "./stock_keras_tuner.py", line 570, in <module>
    main(params, ticker_list)
  File "./stock_keras_tuner.py", line 480, in main
    results_df = tune(params)
  File "./stock_keras_tuner.py", line 388, in tune
    tuner.search(
  File "/Users/jholmes/stock/lib/python3.8/site-packages/keras_tuner/engine/base_tuner.py", line 169, in search
    trial = self.oracle.create_trial(self.tuner_id)
  File "/Users/jholmes/stock/lib/python3.8/site-packages/keras_tuner/engine/oracle.py", line 189, in create_trial
    response = self.populate_space(trial_id)
  File "/Users/jholmes/stock/lib/python3.8/site-packages/keras_tuner/tuners/bayesian.py", line 232, in populate_space
    if result.fun[0] < optimal_val:
TypeError: 'float' object is not subscriptable

**Expected behavior**

No errors.

**Would you like to help us fix it?**
Yes.

**Comment by GearLord** [comment]
I have the same problem. If I use any version <= 1.0.4 it works fine.
I didn't check if this has been resolved in the latest version (1.1.1) released 3 days ago.

**Comment by brydon** [comment]
What version of keras-tuner are you using?

**Comment by codecypher** [comment]
Keras Tuner v 1.1.0

I will try 1.1.1

**Comment by cjc77** [comment]
Any idea when the version of Keras Tuner will be updated on Conda? Currently, v 1.1.0 is the latest version available.

**Comment by codecypher** [comment]
I have been using the setting “ pip_interop_enabled: true” is n .condarc and I also switched to [mambaforge](https://github.com/conda-forge/miniforge)
