### ISSUE TITLE
ValueError from trying to turn trial_id into an int

### ISSUE THREAD

**Issue by kotoroshinoto** [keras-team/keras-tuner#680]
**Describe the bug**
Traceback (most recent call last):
  File "TrainModels.py", line 112, in <module>
    hyper_tuner.search(tf_train, validation_data=tf_valid)
  File "/opt/conda/lib/python3.7/site-packages/keras_tuner/engine/base_tuner.py", line 178, in search
    self.on_trial_begin(trial)
  File "/opt/conda/lib/python3.7/site-packages/keras_tuner/engine/base_tuner.py", line 240, in on_trial_begin
    self._display.on_trial_begin(self.oracle.get_trial(trial.trial_id))
  File "/opt/conda/lib/python3.7/site-packages/keras_tuner/engine/tuner_utils.py", line 109, in on_trial_begin
    self.trial_number = int(trial.trial_id) + 1
ValueError: invalid literal for int() with base 10: '1923f869d8f82ba5c8e64e383ddfe153'

**Expected behavior**
running a search using hypermodel

**Would you like to help us fix it?**
If I can I will help. It looks like the trial ID might be generated in hex, and the int() transformer doesn't know that.

**Comment by kotoroshinoto** [comment]
the changelog for version 1.1.1 says that the trial ids were supposed to change from hex to ints starting at 0, so why would I be getting a trial ID that is still a hex string when my system tells me it has version 1.1.2?

**Comment by kotoroshinoto** [comment]
I might have figured it out, I might have had the wrong version installed when the project directory was created and it may have cached some information that was being reloaded rather than generated fresh.

I deleted the generated project folder and it is now using integers for trial_ids. I'll leave the issue open until it finishes a test run.

**Comment by kotoroshinoto** [comment]
Its not likely that the code generating the hex values will be used, but that should probably still be either removed or altered so that it either will function as expected, or simply not confuse people looking through the codebase.
