### ISSUE TITLE
bizarre error from tuner

### ISSUE THREAD

**Issue by kotoroshinoto** [keras-team/keras-tuner#681]
Using derived classes of HyperModel and BayesianOptimization tuner.

something might be wrong with the run_trial function in bayesian optimization class

TrainModels.py:112: DeprecationWarning: `Tuner.run_trial()` returned None. It should return one of float, dict, keras.callbacks.History, or a list of one of these types. The use case of calling `Tuner.oracle.update_trial()` in `Tuner.run_trial()` is deprecated, and will be removed in the future.
  hyper_tuner.search(tf_train, validation_data=tf_valid)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2928, in variable_creator_scope
    yield
  File "TrainModels.py", line 112, in <module>
    hyper_tuner.search(tf_train, validation_data=tf_valid)
  File "/opt/conda/lib/python3.7/site-packages/keras_tuner/engine/base_tuner.py", line 200, in search
    self.on_trial_end(trial)
  File "/opt/conda/lib/python3.7/site-packages/keras_tuner/engine/base_tuner.py", line 252, in on_trial_end
    self.oracle.end_trial(trial.trial_id, trial_module.TrialStatus.COMPLETED)
  File "/opt/conda/lib/python3.7/site-packages/keras_tuner/engine/oracle.py", line 260, in end_trial
    self.score_trial(trial)
  File "/opt/conda/lib/python3.7/site-packages/keras_tuner/engine/oracle.py", line 164, in score_trial
    trial.score = trial.metrics.get_best_value(self.objective.name)
  File "/opt/conda/lib/python3.7/site-packages/keras_tuner/engine/metrics_tracking.py", line 231, in get_best_value
    self._assert_exists(name)
  File "/opt/conda/lib/python3.7/site-packages/keras_tuner/engine/metrics_tracking.py", line 286, in _assert_exists
    raise ValueError("Unknown metric: %s" % (name,))
ValueError: Unknown metric: val_loss

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TrainModels.py", line 112, in <module>
    hyper_tuner.search(tf_train, validation_data=tf_valid)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 452, in __exit__
    _pop_per_thread_mode()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/distribution_strategy_context.py", line 62, in _pop_per_thread_mode
    ops.get_default_graph()._distribution_strategy_stack.pop(-1)  # pylint: disable=protected-access
IndexError: pop from empty list

**Expected behavior**
run search and return best models

**Would you like to help us fix it?**

**Comment by kotoroshinoto** [comment]
My bad, I forgot to return the result of the call to the super-object's run_trial, so i'm re-running another trial with the int(x,16) fix in place to see if it chokes anywhere else.

if that error remains, there is still a problem with how the trial ID is being allocated.

**Comment by brydon** [comment]
I think you're right, this sounds like #668
