### ISSUE TITLE
error: pop from empty list after tuner search.

### ISSUE THREAD

**Issue by kotoroshinoto** [keras-team/keras-tuner#686]
**Describe the bug**
Traceback (most recent call last):
  File "TrainModels.py", line 112, in <module>
    hyper_tuner.search(tf_train, validation_data=tf_valid)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 452, in __exit__
    _pop_per_thread_mode()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/distribution_strategy_context.py", line 62, in _pop_per_thread_mode
    ops.get_default_graph()._distribution_strategy_stack.pop(-1)  # pylint: disable=protected-access
IndexError: pop from empty list

**To Reproduce**
I'm sorry I can't share  access to the project.  I think this is the most relevant part of the code:
tf_strategy = tf.distribute.MirroredStrategy(devices=["/gpu:0", "/gpu:1"])
with tf_strategy.scope():
    options = tf.data.Options()
    options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.OFF
    tf_train = tokenized_datasets['train'].to_tf_dataset(
        columns=tf_columns,
        label_cols=list(tf_labels),
        shuffle=True,
        collate_fn=data_collator,
        batch_size=32
    )
    tf_train.with_options(options)
    tf_test = tokenized_datasets['test'].to_tf_dataset(
        columns=tf_columns,
        label_cols=list(tf_labels),
        shuffle=False,
        collate_fn=data_collator,
        batch_size=32
    )
    tf_test.with_options(options)
    tf_valid = tokenized_datasets['validation'].to_tf_dataset(
        columns=tf_columns,
        label_cols=list(tf_labels),
        shuffle=False,
        collate_fn=data_collator,
        batch_size=32
    )
    tf_valid.with_options(options)
    hypermodel = UncasedBertHyperModel()
    hyper_tuner = BayesianTunerEpochsAndBatchSize(hypermodel, 'val_mean_squared_error', 10)
    hyper_tuner.search(tf_train, validation_data=tf_valid)

**Expected behavior**
I expected the search function to complete successfully and return without error. It has carried out the trials, but then ran into this error. I don't know what went wrong. This is being run within a google cloud notebook instance, though from the command line access b/c the runtime was long and I needed to be able to check on progress.  (since the gcp instances kick clients off around once a day, the notebooks would stop updating, but the terminals will reconnect).

**Would you like to help us fix it?**
I'm willing to try. I have no idea what is wrong here though.

**Comment by haifeng-jin** [comment]
Would you try use the `distribution_strategy` argument of the `Tuner` initializer instead of explicitly make the scope?
