### ISSUE TITLE
PermissionError in tuner.search() (when consulting usage of partitions)

### ISSUE THREAD

**Issue by franchesoni** [keras-team/keras-tuner#69]
At some place, ```tuner.search``` gets the usage information for different partitions.
I get a ```PermissionError``` in one of the iterations.

My workaround was a try-except, assigning arbitrary memory values (assuming an usage of 100%). It is not elegant at all.
Traceback below

```
Traceback (most recent call last):
  File "mlp_1_search.py", line 135, in <module>
    tuner.search(train_gen, validation_data=test_gen)
  File "lib/python3.6/site-packages/kerastuner/engine/tuner.py", line 223, in search
    self.run_trial(trial, hp, fit_args, fit_kwargs)
  File "lib/python3.6/site-packages/kerastuner/tuners/hyperband.py", line 326, in run_trial
    super(Hyperband, self).run_trial(trial, hp, fit_args, fit_kwargs)
  File "lib/python3.6/site-packages/kerastuner/engine/tuner.py", line 261, in run_trial
    model.fit(*fit_args, **fit_kwargs)
  File "lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 643, in fit
    use_multiprocessing=use_multiprocessing)
  File "lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 604, in fit
    steps_name='steps_per_epoch')
  File "lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 293, in model_iteration
    callbacks._call_batch_hook(mode, 'end', step, batch_logs)
  File "lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 232, in _call_batch_hook
    batch_hook(batch, logs)
  File "lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 515, in on_train_batch_end
    self.on_batch_end(batch, logs=logs)
  File "lib/python3.6/site-packages/kerastuner/engine/tuner_utils.py", line 91, in on_batch_end
    self.tuner.on_batch_end(self.execution, self.model, batch, logs)
  File "lib/python3.6/site-packages/kerastuner/engine/tuner.py", line 293, in on_batch_end
    self._display.on_batch_end(execution, model, batch, logs=logs)
  File "lib/python3.6/site-packages/kerastuner/engine/tuner_utils.py", line 184, in on_batch_end
    host_status = self.host.get_status()
  File "lib/python3.6/site-packages/kerastuner/abstractions/host.py", line 93, in get_status
    status['disk'] = self._get_disk_usage()
  File "lib/python3.6/site-packages/kerastuner/abstractions/host.py", line 198, in _get_disk_usage
    usage = psutil.disk_usage(name)
  File "lib/python3.6/site-packages/psutil/__init__.py", line 2121, in disk_usage
    return _psplatform.disk_usage(path)
  File "lib/python3.6/site-packages/psutil/_psposix.py", line 131, in disk_usage
    st = os.statvfs(path)
PermissionError: [Errno 13] Permission denied: '/media/javier/cordon'
```

**Comment by omalleyt12** [comment]
@franchesoni Thanks for the issue! This should be fixed in the master branch, could you please try again and reopen if you are still seeing issues?
