### ISSUE TITLE
Optimization based on best validation scores

### ISSUE THREAD

**Issue by DagonArises** [keras-team/keras-tuner#733]
When defined a tuner and run the search function, although we can specify 'validation_split', the output prints 'Best score So Far: ...'. I would like to know whether this score is the best training or validation score.  

If I would like to select the best combination of hyperparameters based on the best validation performance, how do I implement this idea? 
Thanks in advance for any help.

**Comment by DagonArises** [comment]
Use 'val_score' in the objective. Tuner does recognize it

**Comment by FENG-MASTER** [comment]
Why don't I recognize when I use 'val_score', and I don't recognize when I use 'score'


RuntimeError: Number of consecutive failures excceeded the limit of 3.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/base_tuner.py", line 250, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/base_tuner.py", line 243, in _run_and_update_trial
    self.oracle.objective,
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/tuner_utils.py", line 265, in convert_to_metrics_dict
    [convert_to_metrics_dict(elem, objective) for elem in results]
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/tuner_utils.py", line 265, in <listcomp>
    [convert_to_metrics_dict(elem, objective) for elem in results]
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/tuner_utils.py", line 279, in convert_to_metrics_dict
    results, objective
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/tuner_utils.py", line 249, in _get_best_value_and_best_epoch_from_history
    objective_value = objective.get_value(metrics)
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/objective.py", line 55, in get_value
    return logs[self.name]
KeyError: 'val_score'

**Comment by FENG-MASTER** [comment]
Why don't I recognize when I use 'val_score', and I don't recognize when I use 'score'


RuntimeError: Number of consecutive failures excceeded the limit of 3.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/base_tuner.py", line 250, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/base_tuner.py", line 243, in _run_and_update_trial
    self.oracle.objective,
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/tuner_utils.py", line 265, in convert_to_metrics_dict
    [convert_to_metrics_dict(elem, objective) for elem in results]
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/tuner_utils.py", line 265, in <listcomp>
    [convert_to_metrics_dict(elem, objective) for elem in results]
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/tuner_utils.py", line 279, in convert_to_metrics_dict
    results, objective
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/tuner_utils.py", line 249, in _get_best_value_and_best_epoch_from_history
    objective_value = objective.get_value(metrics)
  File "/usr/local/lib/python3.6/site-packages/keras_tuner/engine/objective.py", line 55, in get_value
    return logs[self.name]
KeyError: 'val_score'
