### ISSUE TITLE
Double conditional scope on same hpyerparameter

### ISSUE THREAD

**Issue by leleogere** [keras-team/keras-tuner#738]
**Describe the bug**

I am unable to use the same hyperparameter in two nested conditional scopes.

In the following example, I am trying to build a network with between 0 and 3 convolutional layers. When I have at least one convolutional layer, I want to be able to set the pooling size as a new hyperparameter, so I need a first conditional scope on the number of convolutional layers. Then I have a loop over the layers, and in each iteration, I need another conditional scope on the number of convolutional layers in order to select the number of filters each time. But I'm getting the following errors:
```py
ValueError: `HyperParameter` named: num_conv_layers not defined.
```
and
```py
NotImplementedError
```

<details>
<summary>Traceback</summary>

```py
Traceback (most recent call last):
  File "/home/lgere/anaconda3/envs/deep/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py", line 128, in _populate_initial_space
    self.hypermodel.declare_hyperparameters(hp)
  File "/home/lgere/anaconda3/envs/deep/lib/python3.9/site-packages/keras_tuner/engine/hypermodel.py", line 114, in declare_hyperparameters
    raise NotImplementedError
NotImplementedError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/lgere/anaconda3/envs/deep/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-633bbc6c1adc>", line 1, in <cell line: 1>
    runfile('/home/lgere/.config/JetBrains/PyCharm2022.2/scratches/scratch_4.py', wdir='/home/lgere/.config/JetBrains/PyCharm2022.2/scratches')
  File "/home/lgere/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/lgere/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/lgere/.config/JetBrains/PyCharm2022.2/scratches/scratch_4.py", line 36, in <module>
    tuner = keras_tuner.RandomSearch(build, objective='val_loss', max_trials=3, overwrite=True)
  File "/home/lgere/anaconda3/envs/deep/lib/python3.9/site-packages/keras_tuner/tuners/randomsearch.py", line 145, in __init__
    super(RandomSearch, self).__init__(oracle, hypermodel, **kwargs)
  File "/home/lgere/anaconda3/envs/deep/lib/python3.9/site-packages/keras_tuner/engine/tuner.py", line 110, in __init__
    super(Tuner, self).__init__(
  File "/home/lgere/anaconda3/envs/deep/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py", line 103, in __init__
    self._populate_initial_space()
  File "/home/lgere/anaconda3/envs/deep/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py", line 135, in _populate_initial_space
    self.hypermodel.build(hp)
  File "/home/lgere/.config/JetBrains/PyCharm2022.2/scratches/scratch_4.py", line 23, in build
    with hp.conditional_scope('num_conv_layers', list(range(i + 1, max_conv + 1))):
  File "/home/lgere/anaconda3/envs/deep/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/lgere/anaconda3/envs/deep/lib/python3.9/site-packages/keras_tuner/engine/hyperparameters.py", line 628, in conditional_scope
    raise ValueError(
ValueError: `HyperParameter` named: num_conv_layers not defined.
```

</details>

**To Reproduce**

Here is a link to a Colab Notebook to reproduce the issue: https://colab.research.google.com/drive/1YBPq8W5g7IAuxFAli61v7P2k2vhKc_Vt

<details>
<summary>Code used</summary>

```python
import keras_tuner
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras import layers

min_conv = 0
max_conv = 3

min_filters = 16
max_filters = 64

min_pooling_size = 2
max_pooling_size = 3

def build(hp: keras_tuner.HyperParameters):
    model = Sequential(layers.InputLayer((128, 128, 1)))

    num_conv_layers = hp.Int('num_conv_layers', min_conv, max_conv, default=max_conv)

    with hp.conditional_scope('num_conv_layers', list(range(1, max_conv + 1))):
        pooling_size = hp.Int('pooling_size', min_pooling_size, max_pooling_size)
        for i in range(num_conv_layers):
            with hp.conditional_scope('num_conv_layers', list(range(i + 1, max_conv + 1))):
                num_filters = hp.Int(f'num_filters_{i}', min_filters, max_filters)
                model.add(layers.Conv2D(num_filters, kernel_size=3, activation='relu'))
                model.add(layers.MaxPool2D(pooling_size))

    model.add(layers.Flatten())
    model.add(layers.Dense(1, activation='sigmoid'))
    model.compile('adam', loss='binary_crossentropy')
    return model

X = np.random.rand(100, 128, 128, 1)
y = np.random.randint(0, 1, 100)

tuner = keras_tuner.RandomSearch(build, objective='val_loss', max_trials=3, overwrite=True)
tuner.search(X, y, batch_size=32, epochs=3, validation_split=0.2)
```

</details>

**Expected behavior**

I would expect to be able to use the same hyperparameter twice in two nested conditional scopes.

**Additional context**

I know that I could use an extra boolean hyperparameter `use_conv_layers` to specify if there are or not any convolutional layers, and then set `num_conv_layers` to only go between 1 and 3 in a conditional scope of this boolean, but I feel like having an extra variable is not needed as having `num_conv_layers = 0` has exactly the same meaning.

**Comment by haifeng-jin** [comment]
Summary:
Whenever nested conditional scopes are on the same hyperparameter name, it would give the error.
