### ISSUE TITLE
Exception calling application: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by jmimi** [keras-team/keras-tuner#927]
Hi there
I'm using keras tuner with one chief  and two clients (tuners) .
The exception I got in chief:
```
grpc._server                   _call_behavior   508 : Exception calling application: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "[project-dir]/lib/python3.10/site-packages/grpc/_server.py", line 494, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "[project-dir]/lib/python3.10/site-packages/keras_tuner/distribute/oracle_chief.py", line 56, in EndTrial
    self.oracle.end_trial(trial)
  File "[project-dir]/lib/python3.10/site-packages/keras_tuner/engine/oracle.py", line 107, in wrapped_func
    ret_val = func(*args, **kwargs)
  File "[project-dir]/lib/python3.10/site-packages/keras_tuner/engine/oracle.py", line 434, in end_trial
    self._check_consecutive_failures()
  File "[project-dir]/lib/python3.10/site-packages/keras_tuner/engine/oracle.py", line 387, in _check_consecutive_failures
    "Number of consecutive failures excceeded the limit "
TypeError: can only concatenate str (not "NoneType") to str

```
I got this exception in a client:
```
Exception in tuning: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: can only concatenate str (not "NoneType") to str"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: can only concatenate str (not \"NoneType\") to str", grpc_status:2, created_time:"2023-09-01T01:55:30.807344773+01:30"}"
```

The null checking needed to be placed in this line:

https://github.com/keras-team/keras-tuner/blob/09107722b61ad2a3ead007120f0fd55f8446937b/keras_tuner/engine/oracle.py#L389C31-L389C31

**Comment by jmimi** [comment]
As I see this problem is solved in `1.4.6`, [here](https://github.com/keras-team/keras-tuner/blob/aaaef683400926dc11b7ce7c38747a01b7a037cb/keras_tuner/engine/oracle.py#L546). 
Thanks
